### ISSUE TITLE
Pin longstanding issue for Typo Fixes and Grammar Corrections

### ISSUE THREAD

**Issue by dagilleland** [dendronhq/dendron-blog#17]
I propose that you use #15 as a **pinned issue** that can be **locked** which people can reference when making pull requests for simple typo fixes or corrections in grammar (like #16). That way, you don't get littered with small GitHub issues around this general idea of improving documentation.

Just a thought... 😃

**Comment by ScriptAutomate** [comment]
I really love this idea for our docs repos in general! Thanks for the idea. I've pinned and locked that issue, so I'll close this issue as mission complete :smiling_face_with_tear:
